TH_Lab01/Models/Branch.cs
namespace TH_Lab01.Models
{
    public enum Branch
    {
        IT,BE,CE,EE
    }
}

TH_Lab01/Models/ErrorViewModel.cs
namespace TH_Lab01.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TH_Lab01/Models/Gender.cs
namespace TH_Lab01.Models
{
    public enum Gender
    {
        Male,
        Female
    }
}

TH_Lab01/Models/MenuItem.cs
namespace TH_Lab01.Models
{
    public class MenuItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
    }
}

TH_Lab01/Models/Student.cs
using System.ComponentModel.DataAnnotations;

namespace TH_Lab01.Models
{
    public class Student
    {
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required(ErrorMessage ="Email bắt buộc phải được nhập")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string? Email { get; set; } //Email

        [StringLength(100, MinimumLength = 8)]
        [Required]
        public string? Password { get; set; } //Mật khẩu

        [Required]
        public Branch? Branch { get; set; } //Ngành học

        [Required]
        public Gender? Gender { get; set; } //Giới tính

        public bool IsRegular { get; set; } //Hệ: true–chính quy, false–phi chính quy

        [DataType(DataType.MultilineText)]
        [Required]
        public string? Address { get; set; } //Địa chỉ

        [Range(typeof(DateTime), "1/1/1963", "12/31/2005")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime DateOfBorth { get; set; } //Ngày sinh
        public string? ImagePath { get; set; }
    }
}

TH_Lab01/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using TH_Lab01.Models;

namespace TH_Lab01.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TH_Lab01/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using TH_Lab01.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TH_Lab01.Controllers
{
    public class StudentController : Controller
    {
        private static List<Student> listStudents = new List<Student>();
        private readonly IWebHostEnvironment _webHostEnvironment;
        public StudentController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            if (!listStudents.Any())
            {
                listStudents.AddRange(new List<Student>()
                {
                    new Student() { Id = 101, Name = "Hải Nam", Branch = Branch.IT, Gender = Gender.Male, IsRegular = true, Address = "A1-2018", Email = "nam@g.com", DateOfBorth = new DateTime(2000, 1, 1) },
                    new Student() { Id = 102, Name = "Minh Tú", Branch = Branch.BE, Gender = Gender.Female, IsRegular = true, Address = "A1-2019", Email = "tu@g.com", DateOfBorth = new DateTime(2001, 2, 2) },
                    new Student() { Id = 103, Name = "Hoàng Phong", Branch = Branch.CE, Gender = Gender.Male, IsRegular = false, Address = "A1-2020", Email = "phong@g.com", DateOfBorth = new DateTime(2002, 3, 3) },
                    new Student() { Id = 104, Name = "Xuân Mai", Branch = Branch.EE, Gender = Gender.Female, IsRegular = false, Address = "A1-2021", Email = "mai@g.com", DateOfBorth = new DateTime(2003, 4, 4) }
                });
            }
        }
        public ActionResult Index()
        {
            return View(listStudents);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.AllGenders = System.Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();

            return View(); 
        }
        [HttpPost]
        public IActionResult Create(Student s,IFormFile? ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.Length > 0)
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;

                    string uploadPath = Path.Combine(wwwRootPath, "images", "student");

                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(ImageFile.FileName);
                    string filePath = Path.Combine(uploadPath, fileName);

                    s.ImagePath = "/images/student/" + fileName;
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        ImageFile.CopyTo(fileStream);
                    }
                }
                s.Id = listStudents.LastOrDefault() != null ? listStudents.Last().Id + 1 : 101;
                listStudents.Add(s);
                return View("Index", listStudents);
            }
            ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
            ViewBag.AllBranches = new List<SelectListItem>()
            {
                new SelectListItem{ Text="IT",Value="1"},
                new SelectListItem{ Text="BE",Value="2"},
                new SelectListItem{ Text="CE",Value="3"},
                new SelectListItem{ Text="EE",Value="4"}
            };
            return View();
        }
    }
}

TH_Lab01/ViewComponents/RenderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TH_Lab01.Models;

namespace TH_Lab01.ViewComponents
{
    public class RenderViewComponent:ViewComponent
    {
        private List<MenuItem> MenuItems=new List<MenuItem>()
        {
            new MenuItem(){Id=1, Name="Branches", Link="#"},
            new MenuItem(){Id=2, Name="Students", Link="/admin/Student/List"},
            new MenuItem(){Id=3, Name="Subjects", Link="#"},
            new MenuItem(){Id=4, Name="Courses", Link="#"},
        };
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("RenderLeftMenu",MenuItems);
        }
    }    
}

TH_Lab01/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TH_Lab01/Views/Shared/Components/Render/RenderLeftMenu.cshtml
@model IEnumerable<MenuItem>
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">CORE</div>
            <a class="nav-link" href="/Home/Index">
                Dashboard
            </a>
            <div class="sb-sidenav-menu-heading">MANAGEMENT</div>
            @foreach(var item in Model)
            {
                <a class="nav-link" href="@item.Link">
                    @item.Name
                </a>
            }
)
        </div>
    </div>
</nav>

TH_Lab01/Views/Shared/Footer.cshtml
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2025</div>
        </div>
    </div>
</footer>

TH_Lab01/Views/Shared/LeftMenu.cshtml
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">
        <div class="nav">
            <div class="sb-sidenav-menu-heading">CORE</div>
            <a class="nav-link" href="/Home/Index">
                Dashboard
            </a>
            <div class="sb-sidenav-menu-heading">MANAGEMENT</div>
            <a class="nav-link" href="#">
                Students
            </a>
            <a class="nav-link" href="#!">
                Courses
            </a>
        </div>
    </div>
</nav>

TH_Lab01/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Management System</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">

    <partial name="TopNav" />
    <div id="layoutSidenav">

        <div id="layoutSidenav_nav">
            <partial name="LeftMenu" />
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <partial name="Footer" />
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js"></script>

    @RenderSection("Scripts", required: false);
</body>
</html>

TH_Lab01/Views/Shared/MyLayoutHelper.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Management System</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">

    <partial name="TopNav" />
    <div id="layoutSidenav">

        <div id="layoutSidenav_nav">
            @await Component.InvokeAsync("Render")
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <partial name="Footer" />
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js"></script>

    @RenderSection("Scripts", required: false);
</body>
</html>

TH_Lab01/Views/Shared/TopNav.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand ps-3" href="/">Student System</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <ul class="navbar-nav ms-auto me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

TH_Lab01/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TH_Lab01</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TH_Lab01.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TH_Lab01</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - TH_Lab01 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TH_Lab01/Views/Student/Create.cshtml
@using TH_Lab01.Models
@model Student

<h2>Thêm mới Sinh viên</h2>

<div>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Student" asp-action="Create" asp-route-area="admin" method="post" enctype="multipart/form-data" class="mt-3">

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label> 
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" placeholder="Họ tên"> 
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label"></label> 
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Email"> 
            </div>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Password" class="col-sm-2 col-form-label"></label> 
            <div class="col-sm-10">
                <input asp-for="Password" class="form-control" placeholder="Password"> 
            </div>
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Branch" class="col-sm-2 col-form-label"></label> 
            <div class="col-sm-10">
                <select asp-for="Branch" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<Branch>()"></select>
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="IsRegular" class="col-sm-2 col-form-label"></label> 
            <div class="col-sm-10">
                <input type="checkbox" class="custom-control-input" asp-for="IsRegular">
            </div>
            <span asp-validation-for="IsRegular" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="DateOfBorth" class="col-sm-2 col-form-label"></label> 
            <div class="col-sm-10">
                <input asp-for="DateOfBorth" class="form-control"> @* *@
            </div>
            <span asp-validation-for="DateOfBorth" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Gender" class="col-sm-2 col-form-label"></label> @* *@
            <div class="col-sm-10">
                @foreach (var gender in ViewBag.AllGenders)
                {
                    <label class="radio-inline">
                        <input type="radio" asp-for="Gender" value="@gender"
                               id="Gender@(gender)" />@gender<br /> @* *@
                    </label>
                }
            </div>
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label class="col-sm-2 col-form-label">Ảnh đại diện</label>
            <div class="col-sm-10">
                <input type="file" name="ImageFile" class="form-control-file">
            </div>
        </div>

        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label> @* *@
            <div class="col-sm-10">
                <textarea asp-for="Address" class="form-control"
                          placeholder="Địa chỉ"></textarea> @* *@
            </div>
        </div>

        <div style="margin-top: 10px" class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Create</button> @* *@
            </div>
        </div>
    </form>
</div>

TH_Lab01/Views/Student/Index.cshtml
@using TH_Lab01.Models
@model IEnumerable<Student>

<h2>Danh sách Sinh viên</h2>

<p>
    <a asp-controller="Student" 
       asp-action="Create" 
       asp-route-area="admin" 
       class="btn btn-primary">Create Student</a> 
</p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Mã</th>
            <th>Họ tên</th>
            <th>Ngày sinh</th>
            <th>Ngành</th>
            <th>Giới tính</th>
            <th>Hệ ĐT</th>
            <th>Địa chỉ</th>
            <th>Ảnh</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>@s.Id</td>
                <td>@s.Name</td>
                <td>@s.DateOfBorth.ToShortDateString()</td>
                @{
                    string str = "";
                    switch (s.Branch) 
                    {
                        case Branch.IT:
                            str = "CNTT";
                            break;
                        case Branch.BE:
                            str = "Kinh tế";
                            break;
                        case Branch.CE:
                            str = "Công trình";
                            break;
                        case Branch.EE:
                            str = "Điện - Điện tử";
                            break;
                    }
                }
                <td>@str</td>
                <td>@(s.Gender == Gender.Male ? "Nam" : "Nữ")</td>
                <td>@(s.IsRegular ? "Chính quy" : "Phi chính quy")</td>
                <td>@s.Address</td>
                <td>
                    @if (!string.IsNullOrEmpty(s.ImagePath))
                    {
                        <img src="@s.ImagePath" alt="Ảnh sinh viên" style="width: 50px; height: 50px; object-fit: cover;">
                    }
                    else
                    {
                        <span>(No Image)</span>
                    }
                </td>
                <td>@s.Email</td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    <script>
        var table = document.querySelector("table");
        table.onclick = function onTableClick() {
            table.style = "background-color: yellow;"
        }
    </script>
}